### ISSUE TITLE
Encountering error in GCP App Engine

### ISSUE THREAD

**Issue by llwp** [adamyi/golinks#2]
This seems the relevant error, full traceroute attached:
```
AttributeError: 'module' object has no attribute 'DEFAULT_MAX_REDIRECTS'
```

Front end / app error 500s currently - has not yet successfully run. Perhaps also related to the runtime or other selected/default/native options.

![Screenshot from 2019-04-30 14-51-12](https://user-images.githubusercontent.com/9566542/56986131-f9df5280-6b57-11e9-9c49-fabf53680205.png)

**Comment by adamyi** [comment]
Which version of pip are you using? You might be using pip for Python 3 and hence installing py3 version of dependencies which are incompatible with gae py27 runtime.

Remove the old `lib` directory, run `pip install -t lib -r requirements.txt` again (make sure this pip is for python 2.7, you can check with `pip -V`), and deploy

Let me know if this resolves your problem :-)

**Comment by adamyi** [comment]
I'll close this for now. Let me know if the issue still exists
